version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: admin_auth_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: admin_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
